"""
AI Application Builder Service
Generates complete applications from natural language prompts
"""

from emergentintegrations.llm.chat import LlmChat, UserMessage
import os
import json
import logging
from typing import Dict, List

logger = logging.getLogger(__name__)

class AIBuilderService:
    def __init__(self):
        self.api_key = os.getenv("EMERGENT_LLM_KEY")
        
    async def generate_app_structure(self, prompt: str, tech_stack: Dict[str, str]) -> Dict:
        """Generate complete application structure from prompt"""
        
        # Build context for AI
        system_message = f"""You are an expert full-stack developer. Generate a REAL, FUNCTIONAL, WORKING application - not a template or placeholder.

Tech Stack:
- Frontend: {tech_stack.get('frontend', 'React')}
- Backend: {tech_stack.get('backend', 'FastAPI')}
- Database: {tech_stack.get('database', 'MongoDB')}

CRITICAL REQUIREMENTS:
1. Generate COMPLETE, WORKING code - not TODO comments
2. Include ALL logic and functionality
3. Make it IMMEDIATELY RUNNABLE in a preview
4. Use real CSS styling (make it look good)
5. Add ALL necessary imports
6. Generate functional business logic

For example, if user asks for "calculator app":
- Generate actual calculator with working buttons
- Include arithmetic operations (+, -, *, /)
- Style it nicely with CSS
- Make buttons clickable and functional
- Display results properly

Generate a JSON response with this EXACT structure:
{{
  "app_name": "string",
  "description": "string",
  "files": [
    {{
      "path": "string (e.g., frontend/src/App.js)",
      "content": "string (COMPLETE WORKING CODE)",
      "language": "string (javascript, python, etc.)"
    }}
  ],
  "setup_instructions": "string",
  "deployment_notes": "string"
}}

CRITICAL RULES:
- NO placeholder functions or TODO comments
- NO "implement this" messages
- COMPLETE working application
- Professional styling included
- Return ONLY valid JSON, no markdown, no code blocks

Example quality standard - Calculator App should have:
- Working display showing numbers
- Functional buttons (0-9, +, -, *, /, =, C)
- Real calculation logic
- Nice CSS styling
- Responsive design"""

        try:
            chat = LlmChat(
                api_key=self.api_key,
                session_id=f"builder_{hash(prompt)}",
                system_message=system_message
            )
            chat.with_model("openai", "gpt-4o")
            
            user_msg = UserMessage(text=f"Build: {prompt}")
            response = await chat.send_message(user_msg)
            
            # Parse JSON response
            response_text = str(response)
            
            # Clean response if needed
            if "```json" in response_text:
                response_text = response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in response_text:
                response_text = response_text.split("```")[1].split("```")[0].strip()
            
            app_structure = json.loads(response_text)
            
            # Add default files if not present
            if not any(f['path'].endswith('README.md') for f in app_structure['files']):
                app_structure['files'].append({
                    "path": "README.md",
                    "content": self._generate_readme(app_structure, tech_stack),
                    "language": "markdown"
                })
            
            return app_structure
            
        except Exception as e:
            logger.error(f"AI generation error: {e}")
            # Fallback to template if AI fails
            return self._get_fallback_template(prompt, tech_stack)
    
    def _generate_readme(self, app_structure: Dict, tech_stack: Dict) -> str:
        """Generate README for the project"""
        return f"""# {app_structure.get('app_name', 'Generated App')}

{app_structure.get('description', 'Application generated by AI Builder')}

## Tech Stack

- **Frontend**: {tech_stack.get('frontend', 'React')}
- **Backend**: {tech_stack.get('backend', 'FastAPI')}
- **Database**: {tech_stack.get('database', 'MongoDB')}

## Setup Instructions

{app_structure.get('setup_instructions', 'See individual README files in frontend/ and backend/ directories')}

## Deployment

{app_structure.get('deployment_notes', 'See DEPLOYMENT.md for detailed instructions')}

## Generated by AI Builder

This application was generated using AI-powered code generation.
"""
    
    def _get_fallback_template(self, prompt: str, tech_stack: Dict) -> Dict:
        """Fallback template if AI generation fails"""
        app_name = prompt.lower().replace(" ", "-")[:30]
        
        # Basic React frontend
        frontend_files = [
            {
                "path": "frontend/package.json",
                "content": json.dumps({
                    "name": app_name,
                    "version": "1.0.0",
                    "dependencies": {
                        "react": "^19.0.0",
                        "react-dom": "^19.0.0",
                        "axios": "^1.6.0"
                    },
                    "scripts": {
                        "start": "react-scripts start",
                        "build": "react-scripts build"
                    }
                }, indent=2),
                "language": "json"
            },
            {
                "path": "frontend/src/App.js",
                "content": """import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const response = await fetch('/api/data');
      const result = await response.json();
      setData(result);
    } catch (error) {
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Generated Application</h1>
        {loading ? (
          <p>Loading...</p>
        ) : (
          <div>
            <p>Application is running!</p>
          </div>
        )}
      </header>
    </div>
  );
}

export default App;
""",
                "language": "javascript"
            },
            {
                "path": "frontend/src/App.css",
                "content": """.App {
  text-align: center;
}

.App-header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}
""",
                "language": "css"
            }
        ]
        
        # Basic FastAPI backend
        backend_files = [
            {
                "path": "backend/requirements.txt",
                "content": """fastapi>=0.104.0
uvicorn>=0.24.0
motor>=3.3.0
pydantic>=2.5.0
python-dotenv>=1.0.0
""",
                "language": "text"
            },
            {
                "path": "backend/server.py",
                "content": """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "API is running"}

@app.get("/api/data")
async def get_data():
    return {"data": "Generated by AI Builder"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
""",
                "language": "python"
            },
            {
                "path": "backend/.env.example",
                "content": """MONGO_URL=mongodb://localhost:27017
DB_NAME=generated_app
PORT=8000
""",
                "language": "text"
            }
        ]
        
        return {
            "app_name": app_name,
            "description": f"Application generated from: {prompt}",
            "files": frontend_files + backend_files,
            "setup_instructions": "Run 'npm install' in frontend/ and 'pip install -r requirements.txt' in backend/",
            "deployment_notes": "Deploy frontend to Vercel and backend to Render"
        }

ai_builder = AIBuilderService()
