""" 
AI Application Builder Service 
Generates complete, functional applications from natural language prompts using OpenAI 
"""
import os
import json
import re
import logging
from typing import Dict, List
from openai import AsyncOpenAI
from dotenv import load_dotenv
import asyncio

load_dotenv()
logger = logging.getLogger(__name__)

class AIBuilderService:
    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY not found in environment variables")
        self.client = AsyncOpenAI(api_key=self.api_key)

    def _generate_readme(self, app_structure: Dict, tech_stack: Dict[str, str]) -> str:
        """Generate README for the project"""
        return f"""# {app_structure.get('app_name', 'Generated App')}

{app_structure.get('description', 'Application generated by AI Builder')}

## Tech Stack
- **Frontend**: {tech_stack.get('frontend', 'React')}
- **Backend**: {tech_stack.get('backend', 'FastAPI')}
- **Database**: {tech_stack.get('database', 'MongoDB')}

## Setup Instructions
{app_structure.get('setup_instructions', 'See individual README files in frontend/ and backend/ directories')}

## Deployment
{app_structure.get('deployment_notes', 'See DEPLOYMENT.md for detailed instructions')}

## Generated by AI Builder
This application was generated using AI-powered code generation.
"""

    def _generate_package_json(self, app_name: str, has_router: bool = False) -> str:
        """Generate a standard package.json with smart dependencies"""
        package = {
            "name": app_name.lower().replace(" ", "-"),
            "version": "1.0.0",
            "private": True,
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-scripts": "5.0.1"
            },
            "scripts": {
                "start": "react-scripts start",
                "build": "react-scripts build",
                "test": "react-scripts test",
                "eject": "react-scripts eject"
            },
            "eslintConfig": {
                "extends": ["react-app"]
            },
            "browserslist": {
                "production": [">0.2%", "not dead", "not op_mini all"],
                "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
            }
        }
        
        # Auto-add common dependencies
        if has_router:
            package["dependencies"]["react-router-dom"] = "^6.20.0"
        
        return json.dumps(package, indent=2)

    def _extract_imports(self, code: str) -> set:
        """Extract all import statements from code"""
        imports = set()
        import_patterns = [
            r"from\s+['\"]([^'\"]+)['\"]",  # from 'package'
            r"import\s+.*\s+from\s+['\"]([^'\"]+)['\"]",  # import ... from 'package'
            r"import\s+['\"]([^'\"]+)['\"]",  # import 'package'
        ]
        
        for pattern in import_patterns:
            matches = re.findall(pattern, code)
            for match in matches:
                # Extract root package name
                package = match.split('/')[0]
                if not package.startswith('.') and package not in ['react', 'react-dom']:
                    imports.add(package)
        
        return imports

    def _auto_inject_dependencies(self, files: list) -> list:
        """Scan code for imports and ensure package.json has all dependencies"""
        # Find package.json
        package_json_file = None
        for f in files:
            if f['path'].endswith('package.json'):
                package_json_file = f
                break
        
        if not package_json_file:
            return files  # No package.json to update
        
        # Scan all JS files for imports
        all_imports = set()
        for f in files:
            if f['path'].endswith(('.js', '.jsx', '.ts', '.tsx')):
                imports = self._extract_imports(f.get('content', ''))
                all_imports.update(imports)
        
        # Parse existing package.json
        try:
            package_data = json.loads(package_json_file['content'])
            if 'dependencies' not in package_data:
                package_data['dependencies'] = {}
            
            # Common package versions
            COMMON_DEPS = {
                'react-router-dom': '^6.20.0',
                'react-router': '^6.20.0',
                'axios': '^1.6.0',
                'react-icons': '^4.12.0',
                '@reach/router': '^1.3.4',
                'styled-components': '^6.1.0',
                'framer-motion': '^10.16.0',
            }
            
            # Auto-add missing dependencies
            added = []
            for imp in all_imports:
                if imp not in package_data['dependencies']:
                    if imp in COMMON_DEPS:
                        package_data['dependencies'][imp] = COMMON_DEPS[imp]
                        added.append(imp)
                        print(f"🔧 Auto-injected dependency: {imp}")
            
            # Update package.json content
            package_json_file['content'] = json.dumps(package_data, indent=2)
            
            if added:
                print(f"✅ Added {len(added)} missing dependencies: {', '.join(added)}")
        
        except Exception as e:
            print(f"⚠️ Could not auto-inject dependencies: {e}")
        
        return files

    def _add_deployment_configs(self, app_structure: Dict, tech_stack: Dict[str, str]) -> None:
        """Add deployment configuration files to the app structure"""
        files = app_structure.get('files', [])
        
        # Add vercel.json if not present
        if not any(f['path'] == 'vercel.json' for f in files):
            files.append({
                "path": "vercel.json",
                "content": json.dumps({
                    "version": 2,
                    "builds": [
                        {
                            "src": "frontend/package.json",
                            "use": "@vercel/static-build",
                            "config": {
                                "distDir": "build"
                            }
                        }
                    ],
                    "routes": [
                        {
                            "src": "/static/(.*)",
                            "dest": "/frontend/build/static/$1"
                        },
                        {
                            "src": "/(.*)",
                            "dest": "/frontend/build/index.html"
                        }
                    ],
                    "buildCommand": "cd frontend && npm install && npm run build",
                    "outputDirectory": "frontend/build"
                }, indent=2),
                "language": "json"
            })
        
        # Add render.yaml if not present
        if not any(f['path'] == 'render.yaml' for f in files):
            files.append({
                "path": "render.yaml",
                "content": """services:
  - type: web
    name: backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn builder_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: ai_builder_db
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
""",
                "language": "yaml"
            })
        
        # Add .env.example if not present
        if not any(f['path'] == '.env.example' for f in files):
            files.append({
                "path": ".env.example",
                "content": """MONGO_URL=mongodb://localhost:27017
DB_NAME=generated_app
OPENAI_API_KEY=your_openai_api_key_here
JWT_SECRET=your-jwt-secret-key
FRONTEND_URL=http://localhost:3000
""",
                "language": "env"
            })

    async def generate_app_structure(self, prompt: str, tech_stack: Dict[str, str]) -> Dict:
        """Generate complete application structure from prompt"""
        
        system_prompt = f"""You are a WORLD-CLASS full-stack developer who builds UNIQUE, TAILORED applications.

CRITICAL: Analyze the user's request and build EXACTLY what they ask for. Don't use a template!

🎯 REQUEST ANALYSIS:
- Clone apps (Netflix, Spotify): Study the REAL app's structure and features
- Simple tools (calculator, converter): Keep it MINIMAL (1-2 pages max)
- Business sites: Match the industry (restaurant ≠ law firm ≠ gym)
- E-commerce: Product-focused with cart/checkout
- Portfolios: Project showcase focused

📐 SMART SCALING (Not always 5 pages!):
- Calculators/Tools: 1 page with focused functionality
- Landing pages: 1-2 pages max
- Simple businesses: 3-4 pages (Home, Services, About, Contact)
- Complex sites: 5-8 pages (add FAQ, Pricing, Blog, etc.)
- Clones: Match the REAL product (Netflix has Browse, Search, Watch, My List, not generic About page)

🎨 CONTENT UNIQUENESS:
- Netflix clone: Actual genre categories (Action, Comedy, Drama), trending shows, hero video banner
- Restaurant: Real menu items ("Grilled Salmon $28", not "Product 1")
- Portfolio: Project names, tech stacks, descriptions
- Blog: Actual article titles and excerpts

💻 TECHNICAL REQUIREMENTS:
- Use React Router ONLY if multi-page (include in package.json dependencies!)
- Single-page apps DON'T need router
- Component-based architecture
- Modern CSS (Flexbox/Grid)
- Working forms with useState hooks
- Responsive mobile-first design

⚠️ CRITICAL - PACKAGE.JSON DEPENDENCIES:
ALWAYS include ALL libraries used in code:
- If using Router → add "react-router-dom": "^6.20.0"
- If using axios → add "axios": "^1.6.0"
- If using icons → add "react-icons": "^4.12.0"
- Base: "react": "^18.2.0", "react-dom": "^18.2.0", "react-scripts": "5.0.1"

📝 CONTENT QUALITY:
- NO generic "Product 1, Product 2" - use REAL names
- NO Lorem Ipsum - write actual relevant text
- Placeholder images: https://via.placeholder.com/WIDTHxHEIGHT

Tech Stack:
- Frontend: {tech_stack.get('frontend', 'React')}
- Backend: {tech_stack.get('backend', 'FastAPI')}
- Database: {tech_stack.get('database', 'MongoDB')}

JSON STRUCTURE:
{{
  "app_name": "Professional App Name",
  "description": "Detailed description",
  "files": [
    {{
      "path": "frontend/src/App.js",
      "content": "COMPLETE MULTI-PAGE APP CODE",
      "language": "javascript"
    }},
    {{
      "path": "frontend/src/components/Header.js",
      "content": "HEADER COMPONENT",
      "language": "javascript"
    }},
    {{
      "path": "frontend/src/pages/Home.js",
      "content": "HOME PAGE",
      "language": "javascript"
    }},
    {{
      "path": "frontend/src/App.css",
      "content": "PROFESSIONAL STYLING",
      "language": "css"
    }}
  ]
}}

CRITICAL: NO PLACEHOLDERS, NO TODOs, ONLY PRODUCTION-READY CODE"""

        user_prompt = f"""Build a COMPLETE application for: {prompt}

IMPORTANT:
1. Analyze what this request needs - don't use a generic template
2. If it's a clone, research the real product's structure
3. Scale appropriately (simple tools = 1 page, complex sites = multiple pages)
4. Include ALL dependencies in package.json (especially react-router-dom if using Router!)
5. Generate unique, specific content (not generic placeholders)

REQUIREMENTS:
1. Create AT LEAST 5 pages with full navigation
2. Generate REALISTIC content for each page (not lorem ipsum)
3. Include working forms, buttons, and interactions
4. Add beautiful, modern styling
5. Make it production-ready

If it's a website: Include Home (hero + features), About (company story), Products/Services (6+ items), Testimonials, Contact (working form), FAQ
If it's a web app: Include auth pages, dashboard, main features, settings, user profile
If it's e-commerce: Product catalog, product details, cart, checkout, user account

Return ONLY valid JSON with complete, working code for all files."""

        try:
            logger.info(f"Generating app for prompt: {prompt}")
            
            response = await self.client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.8,
                max_tokens=16000  # Increased for complex multi-page apps
            )
            
            response_text = response.choices[0].message.content.strip()
            logger.info(f"Received response, length: {len(response_text)}")
            
            # Clean response if needed
            if "```json" in response_text:
                response_text = response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in response_text:
                response_text = response_text.split("```")[1].split("```")[0].strip()
            
            # Parse JSON
            app_structure = json.loads(response_text)
            
            # Validate structure
            if not app_structure.get('files'):
                raise ValueError("No files generated in response")
            
            # Ensure package.json exists
            has_package_json = any(f['path'].endswith('package.json') for f in app_structure['files'])
            has_router = any('react-router' in f.get('content', '').lower() or 'BrowserRouter' in f.get('content', '') 
                           for f in app_structure['files'])
            
            if not has_package_json:
                app_structure['files'].append({
                    "path": "frontend/package.json",
                    "content": self._generate_package_json(app_structure.get('app_name', 'generated-app'), has_router=has_router),
                    "language": "json"
                })
            
            # AUTO-INJECT MISSING DEPENDENCIES (CRITICAL FIX)
            print("\n🔍 Scanning for missing dependencies...")
            app_structure['files'] = self._auto_inject_dependencies(app_structure['files'])
            
            # Add deployment configs if not present
            self._add_deployment_configs(app_structure, tech_stack)
            
            # Add README if not present
            if not any(f['path'].endswith('README.md') for f in app_structure['files']):
                app_structure['files'].append({
                    "path": "README.md",
                    "content": self._generate_readme(app_structure, tech_stack),
                    "language": "markdown"
                })
            
            logger.info(f"Successfully generated app with {len(app_structure['files'])} files")
            return app_structure
            
        except json.JSONDecodeError as e:
            logger.error(f"JSON parsing error: {e}")
            logger.error(f"Response text: {response_text[:500]}")
            return self._get_fallback_template(prompt, tech_stack)
        except Exception as e:
            logger.error(f"AI generation error: {e}")
            return self._get_fallback_template(prompt, tech_stack)

    def _get_fallback_template(self, prompt: str, tech_stack: Dict[str, str]) -> Dict:
        """Fallback template if AI generation fails"""
        app_name = prompt.lower().replace(" ", "-")[:30]
        
        # Basic React frontend
        frontend_files = [
            {
                "path": "frontend/package.json",
                "content": self._generate_package_json(app_name),
                "language": "json"
            },
            {
                "path": "frontend/src/App.js",
                "content": """import React, { useState } from 'react';
import './App.css';

function App() {
  const [display, setDisplay] = useState('0');
  const [previousValue, setPreviousValue] = useState(null);
  const [operation, setOperation] = useState(null);
  const [waitingForOperand, setWaitingForOperand] = useState(false);

  const inputDigit = (digit) => {
    if (waitingForOperand) {
      setDisplay(String(digit));
      setWaitingForOperand(false);
    } else {
      setDisplay(display === '0' ? String(digit) : display + digit);
    }
  };

  const inputDecimal = () => {
    if (waitingForOperand) {
      setDisplay('0.');
      setWaitingForOperand(false);
    } else if (display.indexOf('.') === -1) {
      setDisplay(display + '.');
    }
  };

  const clear = () => {
    setDisplay('0');
    setPreviousValue(null);
    setOperation(null);
    setWaitingForOperand(false);
  };

  const performOperation = (nextOperation) => {
    const inputValue = parseFloat(display);

    if (previousValue === null) {
      setPreviousValue(inputValue);
    } else if (operation) {
      const currentValue = previousValue || 0;
      const newValue = calculate(currentValue, inputValue, operation);
      setDisplay(String(newValue));
      setPreviousValue(newValue);
    }

    setWaitingForOperand(true);
    setOperation(nextOperation);
  };

  const calculate = (firstValue, secondValue, operation) => {
    switch (operation) {
      case '+':
        return firstValue + secondValue;
      case '-':
        return firstValue - secondValue;
      case '*':
        return firstValue * secondValue;
      case '/':
        return firstValue / secondValue;
      case '=':
        return secondValue;
      default:
        return secondValue;
    }
  };

  return (
    <div className="calculator">
      <div className="calculator-display">{display}</div>
      <div className="calculator-keypad">
        <div className="input-keys">
          <div className="function-keys">
            <button className="calculator-key key-clear" onClick={clear}>AC</button>
            <button className="calculator-key key-sign" onClick={() => setDisplay(String(parseFloat(display) * -1))}>±</button>
            <button className="calculator-key key-percent" onClick={() => setDisplay(String(parseFloat(display) / 100))}>%</button>
          </div>
          <div className="digit-keys">
            <button className="calculator-key key-0" onClick={() => inputDigit(0)}>0</button>
            <button className="calculator-key key-dot" onClick={inputDecimal}>●</button>
            {[1, 2, 3, 4, 5, 6, 7, 8, 9].map(num => (
              <button key={num} className="calculator-key" onClick={() => inputDigit(num)}>{num}</button>
            ))}
          </div>
        </div>
        <div className="operator-keys">
          <button className="calculator-key key-divide" onClick={() => performOperation('/')}>÷</button>
          <button className="calculator-key key-multiply" onClick={() => performOperation('*')}>×</button>
          <button className="calculator-key key-subtract" onClick={() => performOperation('-')}>-</button>
          <button className="calculator-key key-add" onClick={() => performOperation('+')}>+</button>
          <button className="calculator-key key-equals" onClick={() => performOperation('=')}>=</button>
        </div>
      </div>
    </div>
  );
}

export default App;
""",
                "language": "javascript"
            },
            {
                "path": "frontend/src/App.css",
                "content": """* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.calculator {
  width: 320px;
  background: #fff;
  border-radius: 20px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  overflow: hidden;
}

.calculator-display {
  background: #222;
  color: #fff;
  font-size: 48px;
  padding: 30px 20px;
  text-align: right;
  font-weight: 300;
  min-height: 100px;
  display: flex;
  align-items: center;
  justify-content: flex-end;
}

.calculator-keypad {
  display: flex;
}

.input-keys {
  flex: 3;
}

.function-keys {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
}

.digit-keys {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-template-areas:
    "key-1 key-2 key-3"
    "key-4 key-5 key-6"
    "key-7 key-8 key-9"
    "key-0 key-0 key-dot";
}

.calculator-key {
  border: none;
  background: #f0f0f0;
  color: #333;
  font-size: 24px;
  font-weight: 400;
  padding: 20px;
  cursor: pointer;
  transition: all 0.2s;
  border-right: 1px solid #ddd;
  border-bottom: 1px solid #ddd;
}

.calculator-key:hover {
  background: #e0e0e0;
}

.calculator-key:active {
  background: #d0d0d0;
}

.key-0 {
  grid-area: key-0;
}

.function-keys .calculator-key {
  background: #e0e0e0;
  color: #666;
}

.operator-keys {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.operator-keys .calculator-key {
  background: #ff9500;
  color: #fff;
  font-size: 28px;
  border-right: none;
}

.operator-keys .calculator-key:hover {
  background: #ff8000;
}

.key-equals {
  flex: 1;
  background: #ff9500 !important;
}
""",
                "language": "css"
            }
        ]

        # Basic FastAPI backend
        backend_files = [
            {
                "path": "backend/requirements.txt",
                "content": """fastapi>=0.104.0
uvicorn>=0.24.0
motor>=3.3.0
pydantic>=2.5.0
python-dotenv>=1.0.0
openai>=1.12.0
python-jose>=3.3.0
passlib>=1.7.4
bcrypt>=4.0.1
""",
                "language": "text"
            },
            {
                "path": "backend/server.py",
                "content": """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os

app = FastAPI()

# Configure CORS
origins = os.getenv("CORS_ORIGINS", "http://localhost:3000").split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "API is running"}

@app.get("/api/data")
async def get_data():
    return {"data": "Generated by AI Builder"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
""",
                "language": "python"
            },
            {
                "path": "backend/.env.example",
                "content": """MONGO_URL=mongodb://localhost:27017
DB_NAME=generated_app
PORT=8000
OPENAI_API_KEY=your_openai_api_key_here
JWT_SECRET=your-jwt-secret-key
""",
                "language": "text"
            }
        ]

        return {
            "app_name": app_name,
            "description": f"Application generated from: {prompt}",
            "files": frontend_files + backend_files,
            "setup_instructions": "Run 'npm install' in frontend/ and 'pip install -r requirements.txt' in backend/",
            "deployment_notes": "Deploy frontend to Vercel and backend to Render"
        }

# Create a singleton instance
ai_builder = AIBuilderService()